version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: covid_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python-dbt:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:secretpassword@postgres:5432/covid_data

volumes:
  postgres_data:
